<a href="https://colab.research.google.com/github/zheswien/Trainocate_AIML/blob/main/AIML_02_data_wrangling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Load data

In [ ]:
!wget -O teleCust1000t.csv https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DA0101EN/auto.csv

--2023-08-23 08:09:26--  https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DA0101EN/auto.csv
Resolving s3-api.us-geo.objectstorage.softlayer.net (s3-api.us-geo.objectstorage.softlayer.net)... 67.228.254.196
Connecting to s3-api.us-geo.objectstorage.softlayer.net (s3-api.us-geo.objectstorage.softlayer.net)|67.228.254.196|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 24916 (24K) [text/csv]
Saving to: ‘teleCust1000t.csv’

teleCust1000t.csv   100%[===================>]  24.33K  --.-KB/s    in 0.09s

2023-08-23 08:09:26 (270 KB/s) - ‘teleCust1000t.csv’ saved [24916/24916]

In [ ]:
import pandas as pd

In [ ]:
mydata = pd.read_csv("teleCust1000t.csv", header=None)
mydata.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,52.4,2823,ohcv,six,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,54.3,2337,ohc,four,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,54.3,2824,ohc,five,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

# Fix headers

In [ ]:
name_col = ["symboling","normalized-losses","make","fuel-type","aspiration", "num-of-doors","body-style",
         "drive-wheels","engine-location","wheel-base", "length","width","height","curb-weight","engine-type",
         "num-of-cylinders", "engine-size","fuel-system","bore","stroke","compression-ratio","horsepower",
         "peak-rpm","city-mpg","highway-mpg","price"]

mydata.columns = name_col

mydata.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,height,curb-weight,engine-type,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,52.4,2823,ohcv,six,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,54.3,2337,ohc,four,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,54.3,2824,ohc,five,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

In [ ]:
# change settings to show all columns, no hidden ...
pd.set_option('display.max_columns', None)
mydata.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,height,curb-weight,engine-type,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,52.4,2823,ohcv,six,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,54.3,2337,ohc,four,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,54.3,2824,ohc,five,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

In [ ]:
mydata.shape

(205, 26)

In [ ]:
mydata.tail()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,height,curb-weight,engine-type,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,55.5,2952,ohc,four,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.8,55.5,3049,ohc,four,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,55.5,3012,ohcv,six,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,188.8,68.9,55.5,3217,ohc,six,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.9,55.5,3062,ohc,four,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

# Missing values
## Find

In [ ]:
mydata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   normalized-losses  205 non-null    object
 2   make               205 non-null    object
 3   fuel-type          205 non-null    object
 4   aspiration         205 non-null    object
 5   num-of-doors       205 non-null    object
 6   body-style         205 non-null    object
 7   drive-wheels       205 non-null    object
 8   engine-location    205 non-null    object
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64
 14  engine-type        205 non-null    object
 15  num-of-cylinders   205 non-null    object
 16  engine-size        205 non-null    int64
 17  fuel-system        205 non-null    object
 18  bore               205 non-null    object
 19  stroke             205 non-null    object
 20  compression-ratio  205 non-null    float64
 21  horsepower         205 non-null    object
 22  peak-rpm           205 non-null    object
 23  city-mpg           205 non-null    int64
 24  highway-mpg        205 non-null    int64
 25  price              205 non-null    object
dtypes: float64(5), int64(5), object(16)
memory usage: 41.8+ KB

In [ ]:
# check each cell in df
mydata.isnull()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,height,curb-weight,engine-type,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
201,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
202,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
203,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
204,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
mydata.isnull().sum()

symboling            0
normalized-losses    0
make                 0
fuel-type            0
aspiration           0
num-of-doors         0
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 0
stroke               0
compression-ratio    0
horsepower           0
peak-rpm             0
city-mpg             0
highway-mpg          0
price                0
dtype: int64

In [ ]:
mydata.describe(include='all')

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,height,curb-weight,engine-type,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
count,205.000000,205,205,205,205,205,205,205,205,205.000000,205.000000,205.000000,205.000000,205.000000,205,205,205.000000,205,205,205,205.000000,205,205,205.000000,205.000000,205
unique,NaN,52,22,2,2,3,5,3,2,NaN,NaN,NaN,NaN,NaN,7,7,NaN,8,39,37,NaN,60,24,NaN,NaN,187
top,NaN,?,toyota,gas,std,four,sedan,fwd,front,NaN,NaN,NaN,NaN,NaN,ohc,four,NaN,mpfi,3.62,3.40,NaN,68,5500,NaN,NaN,?
freq,NaN,41,32,185,168,114,96,120,202,NaN,NaN,NaN,NaN,NaN,148,159,NaN,94,23,20,NaN,19,37,NaN,NaN,4
mean,0.834146,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98.756585,174.049268,65.907805,53.724878,2555.565854,NaN,NaN,126.907317,NaN,NaN,NaN,10.142537,NaN,NaN,25.219512,30.751220,NaN
std,1.245307,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.021776,12.337289,2.145204,2.443522,520.680204,NaN,NaN,41.642693,NaN,NaN,NaN,3.972040,NaN,NaN,6.542142,6.886443,NaN
min,-2.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86.600000,141.100000,60.300000,47.800000,1488.000000,NaN,NaN,61.000000,NaN,NaN,NaN,7.000000,NaN,NaN,13.000000,16.000000,NaN
25%,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94.500000,166.300000,64.100000,52.000000,2145.000000,NaN,NaN,97.000000,NaN,NaN,NaN,8.600000,NaN,NaN,19.000000,25.000000,NaN
50%,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,97.000000,173.200000,65.500000,54.100000,2414.000000,NaN,NaN,120.000000,NaN,NaN,NaN,9.000000,NaN,NaN,24.000000,30.000000,NaN
75%,2.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.400000,183.100000,66.900000,55.500000,2935.000000,NaN,NaN,141.000000,NaN,NaN,NaN,9.400000,NaN,NaN,30.000000,34.000000,NaN
max,3.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,120.900000,208.100000,72.300000,59.800000,4066.000000,NaN,NaN,326.000000,NaN,NaN,NaN,23.000000,NaN,NaN,49.000000,54.000000,NaN

In [ ]:
mydata.head(20)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,height,curb-weight,engine-type,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,52.4,2823,ohcv,six,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,54.3,2337,ohc,four,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,54.3,2824,ohc,five,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
5,2,?,audi,gas,std,two,sedan,fwd,front,99.8,177.3,66.3,53.1,2507,ohc,five,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250
6,1,158,audi,gas,std,four,sedan,fwd,front,105.8,192.7,71.4,55.7,2844,ohc,five,136,mpfi,3.19,3.40,8.5,110,5500,19,25,17710
7,1,?,audi,gas,std,four,wagon,fwd,front,105.8,192.7,71.4,55.7,2954,ohc,five,136,mpfi,3.19,3.40,8.5,110,5500,19,25,18920
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,192.7,71.4,55.9,3086,ohc,five,131,mpfi,3.13,3.40,8.3,140,5500,17,20,23875
9,0,?,audi,gas,turbo,two,hatchback,4wd,front,99.5,178.2,67.9,52.0,3053,ohc,five,131,mpfi,3.13,3.40,7.0,160,5500,16,22,?
10,2,192,bmw,gas,std,two,sedan,rwd,front,101.2,176.8,64.8,54.3,2395,ohc,four,108,mpfi,3.50,2.80,8.8,101,5800,23,29,16430
11,0,192,bmw,gas,std,four,sedan,rwd,front,101.2,176.8,64.8,54.3,2395,ohc,four,108,mpfi,3.50,2.80,8.8,101,5800,23,29,16925
12,0,188,bmw,gas,std,two,sedan,rwd,front,101.2,176.8,64.8,54.3,2710,ohc,six,164,mpfi,3.31,3.19,9.0,121,4250,21,28,20970
13,0,188,bmw,gas,std,four,sedan,rwd,front,101.2,176.8,64.8,54.3,2765,ohc,six,164,mpfi,3.31,3.19,9.0,121,4250,21,28,21105
14,1,?,bmw,gas,std,four,sedan,rwd,front,103.5,189.0,66.9,55.7,3055,ohc,six,164,mpfi,3.31,3.19,9.0,121,4250,20,25,24565
15,0,?,bmw,gas,std,four,sedan,rwd,front,103.5,189.0,66.9,55.7,3230,ohc,six,209,mpfi,3.62,3.39,8.0,182,5400,16,22,30760
16,0,?,bmw,gas,std,two,sedan,rwd,front,103.5,193.8,67.9,53.7,3380,ohc,six,209,mpfi,3.62,3.39,8.0,182,5400,16,22,41315
17,0,?,bmw,gas,std,four,sedan,rwd,front,110.0,197.0,70.9,56.3,3505,ohc,six,209,mpfi,3.62,3.39,8.0,182,5400,15,20,36880
18,2,121,chevrolet,gas,std,two,hatchback,fwd,front,88.4,141.1,60.3,53.2,1488,l,three,61,2bbl,2.91,3.03,9.5,48,5100,47,53,5151
19,1,98,chevrolet,gas,std,two,hatchback,fwd,front,94.5,155.9,63.6,52.0,1874,ohc,four,90,2bbl,3.03,3.11,9.6,70,5400,38,43,6295

## Replace

In [ ]:
import numpy as np
mydata.replace("?", np.nan, inplace=True)

In [ ]:
mydata.isnull().sum()

symboling             0
normalized-losses    41
make                  0
fuel-type             0
aspiration            0
num-of-doors          2
body-style            0
drive-wheels          0
engine-location       0
wheel-base            0
length                0
width                 0
height                0
curb-weight           0
engine-type           0
num-of-cylinders      0
engine-size           0
fuel-system           0
bore                  4
stroke                4
compression-ratio     0
horsepower            2
peak-rpm              2
city-mpg              0
highway-mpg           0
price                 4
dtype: int64

In [ ]:
mydata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   normalized-losses  164 non-null    object
 2   make               205 non-null    object
 3   fuel-type          205 non-null    object
 4   aspiration         205 non-null    object
 5   num-of-doors       203 non-null    object
 6   body-style         205 non-null    object
 7   drive-wheels       205 non-null    object
 8   engine-location    205 non-null    object
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64
 14  engine-type        205 non-null    object
 15  num-of-cylinders   205 non-null    object
 16  engine-size        205 non-null    int64
 17  fuel-system        205 non-null    object
 18  bore               201 non-null    object
 19  stroke             201 non-null    object
 20  compression-ratio  205 non-null    float64
 21  horsepower         203 non-null    object
 22  peak-rpm           203 non-null    object
 23  city-mpg           205 non-null    int64
 24  highway-mpg        205 non-null    int64
 25  price              201 non-null    object
dtypes: float64(5), int64(5), object(16)
memory usage: 41.8+ KB

## Columns with missing values:

<ol>
    <li>"normalized-losses": 40 missing data</li>
    <li>"num-of-doors": 2 missing data</li>
    <li>"bore": 4 missing data</li>
    <li>"stroke" : 4 missing data</li>
    <li>"horsepower": 2 missing data</li>
    <li>"peak-rpm": 2 missing data</li>
    <li>"price": 4 missing data</li>
</ol>

**Build 2 Models & find which provides higher accuracy**
<ol>
<li> with removed missing value </li>
<li> with mean </li>
</ol>

In [ ]:
mean_norm = mydata['normalized-losses'].mean()

TypeError: ignored

In [ ]:
mean_norm = mydata['normalized-losses'].astype('float64').mean()
mean_norm

122.0

In [ ]:
mydata['normalized-losses'].replace(np.nan, mean_norm, inplace=True)

In [ ]:
mydata.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,height,curb-weight,engine-type,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,122.0,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,52.4,2823,ohcv,six,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,54.3,2337,ohc,four,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,54.3,2824,ohc,five,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

In [ ]:
mydata.isnull().sum()

symboling            0
normalized-losses    0
make                 0
fuel-type            0
aspiration           0
num-of-doors         2
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 4
stroke               4
compression-ratio    0
horsepower           2
peak-rpm             2
city-mpg             0
highway-mpg          0
price                4
dtype: int64

In [ ]:
mydata.describe(include='all')

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,height,curb-weight,engine-type,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
count,205.000000,205.0,205,205,205,203,205,205,205,205.000000,205.000000,205.000000,205.000000,205.000000,205,205,205.000000,205,201,201,205.000000,203,203,205.000000,205.000000,201
unique,NaN,52.0,22,2,2,2,5,3,2,NaN,NaN,NaN,NaN,NaN,7,7,NaN,8,38,36,NaN,59,23,NaN,NaN,186
top,NaN,122.0,toyota,gas,std,four,sedan,fwd,front,NaN,NaN,NaN,NaN,NaN,ohc,four,NaN,mpfi,3.62,3.40,NaN,68,5500,NaN,NaN,8921
freq,NaN,41.0,32,185,168,114,96,120,202,NaN,NaN,NaN,NaN,NaN,148,159,NaN,94,23,20,NaN,19,37,NaN,NaN,2
mean,0.834146,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98.756585,174.049268,65.907805,53.724878,2555.565854,NaN,NaN,126.907317,NaN,NaN,NaN,10.142537,NaN,NaN,25.219512,30.751220,NaN
std,1.245307,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.021776,12.337289,2.145204,2.443522,520.680204,NaN,NaN,41.642693,NaN,NaN,NaN,3.972040,NaN,NaN,6.542142,6.886443,NaN
min,-2.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86.600000,141.100000,60.300000,47.800000,1488.000000,NaN,NaN,61.000000,NaN,NaN,NaN,7.000000,NaN,NaN,13.000000,16.000000,NaN
25%,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94.500000,166.300000,64.100000,52.000000,2145.000000,NaN,NaN,97.000000,NaN,NaN,NaN,8.600000,NaN,NaN,19.000000,25.000000,NaN
50%,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,97.000000,173.200000,65.500000,54.100000,2414.000000,NaN,NaN,120.000000,NaN,NaN,NaN,9.000000,NaN,NaN,24.000000,30.000000,NaN
75%,2.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.400000,183.100000,66.900000,55.500000,2935.000000,NaN,NaN,141.000000,NaN,NaN,NaN,9.400000,NaN,NaN,30.000000,34.000000,NaN
max,3.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,120.900000,208.100000,72.300000,59.800000,4066.000000,NaN,NaN,326.000000,NaN,NaN,NaN,23.000000,NaN,NaN,49.000000,54.000000,NaN

In [ ]:
mydata['num-of-doors'].value_counts()

four    114
two      89
Name: num-of-doors, dtype: int64

In [ ]:
# return the most frequent category
freq_doors = mydata['num-of-doors'].value_counts().idxmax()
print(freq_doors)

mydata['num-of-doors'].replace(np.nan, freq_doors, inplace=True)

four

In [ ]:
mydata.isnull().sum()

symboling            0
normalized-losses    0
make                 0
fuel-type            0
aspiration           0
num-of-doors         0
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 4
stroke               4
compression-ratio    0
horsepower           2
peak-rpm             2
city-mpg             0
highway-mpg          0
price                4
dtype: int64

In [ ]:
mean_bore = mydata['bore'].astype('float64').mean()
mean_stroke = mydata['stroke'].astype('float64').mean()
mean_horsepower = mydata['horsepower'].astype('float64').mean()
mean_peak = mydata['peak-rpm'].astype('float64').mean()

print(mean_bore)
print(mean_stroke)
print(mean_horsepower)
print(mean_peak)

3.3297512437810943
3.255422885572139
104.25615763546799
5125.369458128079

In [ ]:
mydata['bore'].replace(np.nan, mean_bore, inplace=True)
mydata['stroke'].replace(np.nan, mean_stroke, inplace=True)
mydata['horsepower'].replace(np.nan, mean_horsepower, inplace=True)
mydata['peak-rpm'].replace(np.nan, mean_peak, inplace=True)

mydata.isnull().sum()

symboling            0
normalized-losses    0
make                 0
fuel-type            0
aspiration           0
num-of-doors         0
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 0
stroke               0
compression-ratio    0
horsepower           0
peak-rpm             0
city-mpg             0
highway-mpg          0
price                4
dtype: int64

In [ ]:
# drop blank price data (cuz is prediction result)
mydata.dropna(subset=['price'], axis=0, inplace=True)
mydata.isnull().sum()

symboling            0
normalized-losses    0
make                 0
fuel-type            0
aspiration           0
num-of-doors         0
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 0
stroke               0
compression-ratio    0
horsepower           0
peak-rpm             0
city-mpg             0
highway-mpg          0
price                0
dtype: int64

In [ ]:
mydata.shape

(201, 26)

# Data Formatting

In [ ]:
mydata.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 201 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          201 non-null    int64
 1   normalized-losses  201 non-null    object
 2   make               201 non-null    object
 3   fuel-type          201 non-null    object
 4   aspiration         201 non-null    object
 5   num-of-doors       201 non-null    object
 6   body-style         201 non-null    object
 7   drive-wheels       201 non-null    object
 8   engine-location    201 non-null    object
 9   wheel-base         201 non-null    float64
 10  length             201 non-null    float64
 11  width              201 non-null    float64
 12  height             201 non-null    float64
 13  curb-weight        201 non-null    int64
 14  engine-type        201 non-null    object
 15  num-of-cylinders   201 non-null    object
 16  engine-size        201 non-null    int64
 17  fuel-system        201 non-null    object
 18  bore               201 non-null    object
 19  stroke             201 non-null    object
 20  compression-ratio  201 non-null    float64
 21  horsepower         201 non-null    object
 22  peak-rpm           201 non-null    object
 23  city-mpg           201 non-null    int64
 24  highway-mpg        201 non-null    int64
 25  price              201 non-null    object
dtypes: float64(5), int64(5), object(16)
memory usage: 42.4+ KB

In [ ]:
mydata.dtypes

symboling              int64
normalized-losses     object
make                  object
fuel-type             object
aspiration            object
num-of-doors          object
body-style            object
drive-wheels          object
engine-location       object
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
engine-type           object
num-of-cylinders      object
engine-size            int64
fuel-system           object
bore                  object
stroke                object
compression-ratio    float64
horsepower            object
peak-rpm              object
city-mpg               int64
highway-mpg            int64
price                 object
dtype: object

In [ ]:
mydata['normalized-losses'] = mydata['normalized-losses'].astype('float')
mydata['bore'] = mydata['bore'].astype('float')
mydata['stroke'] = mydata['stroke'].astype('float')
mydata['horsepower'] = mydata['horsepower'].astype('float')
mydata['peak-rpm'] = mydata['peak-rpm'].astype('float')
mydata.dtypes

symboling              int64
normalized-losses    float64
make                  object
fuel-type             object
aspiration            object
num-of-doors          object
body-style            object
drive-wheels          object
engine-location       object
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
engine-type           object
num-of-cylinders      object
engine-size            int64
fuel-system           object
bore                 float64
stroke               float64
compression-ratio    float64
horsepower           float64
peak-rpm             float64
city-mpg               int64
highway-mpg            int64
price                 object
dtype: object

In [ ]:
mydata.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,height,curb-weight,engine-type,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495
1,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500
2,1,122.0,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,52.4,2823,ohcv,six,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,54.3,2337,ohc,four,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,54.3,2824,ohc,five,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450

In [ ]:
mydata['city-L/100km'] = 235/mydata['city-mpg']
mydata['highway-L/100km'] = 235/mydata['highway-mpg']

mydata.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,height,curb-weight,engine-type,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,highway-L/100km
0,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495,11.190476,8.703704
1,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500,11.190476,8.703704
2,1,122.0,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,52.4,2823,ohcv,six,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500,12.368421,9.038462
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,54.3,2337,ohc,four,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950,9.791667,7.833333
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,54.3,2824,ohc,five,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450,13.055556,10.681818

In [ ]:
mydata.drop('city-mpg', axis=1, inplace=True)
mydata.drop('highway-mpg', axis=1, inplace=True)
mydata.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,height,curb-weight,engine-type,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,price,city-L/100km,highway-L/100km
0,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111.0,5000.0,13495,11.190476,8.703704
1,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111.0,5000.0,16500,11.190476,8.703704
2,1,122.0,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,52.4,2823,ohcv,six,152,mpfi,2.68,3.47,9.0,154.0,5000.0,16500,12.368421,9.038462
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,54.3,2337,ohc,four,109,mpfi,3.19,3.40,10.0,102.0,5500.0,13950,9.791667,7.833333
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,54.3,2824,ohc,five,136,mpfi,3.19,3.40,8.0,115.0,5500.0,17450,13.055556,10.681818

In [ ]:
# mydata = mydata[["symboling","normalized-losses","make","fuel-type","aspiration", "num-of-doors","body-style",
#          "drive-wheels","engine-location","wheel-base", "length","width","height","curb-weight","engine-type",
#          "num-of-cylinders", "engine-size","fuel-system","bore","stroke","compression-ratio","horsepower",
#          "peak-rpm","city-L/100km","highway-L/100km","price"]]
# mydata.head()

In [ ]:
# Move the index column to the last position
index_col = mydata.pop('price')  # Remove the index column from the DataFrame
mydata['price'] = index_col      # Add the index column to the last position

mydata.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,height,curb-weight,engine-type,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-L/100km,highway-L/100km,price
0,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111.0,5000.0,11.190476,8.703704,13495
1,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111.0,5000.0,11.190476,8.703704,16500
2,1,122.0,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,52.4,2823,ohcv,six,152,mpfi,2.68,3.47,9.0,154.0,5000.0,12.368421,9.038462,16500
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,54.3,2337,ohc,four,109,mpfi,3.19,3.40,10.0,102.0,5500.0,9.791667,7.833333,13950
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,54.3,2824,ohc,five,136,mpfi,3.19,3.40,8.0,115.0,5500.0,13.055556,10.681818,17450

# Data Normalization (Do not mix the approaches in 1 dataset!)

In [ ]:
mydata['width'].head(20)

0     64.1
1     64.1
2     65.5
3     66.2
4     66.4
5     66.3
6     71.4
7     71.4
8     71.4
10    64.8
11    64.8
12    64.8
13    64.8
14    66.9
15    66.9
16    67.9
17    70.9
18    60.3
19    63.6
20    63.6
Name: width, dtype: float64

In [ ]:
mydata[['width', 'length', 'height']].head(10)

    width  length  height
0    64.1   168.8    48.8
1    64.1   168.8    48.8
2    65.5   171.2    52.4
3    66.2   176.6    54.3
4    66.4   176.6    54.3
5    66.3   177.3    53.1
6    71.4   192.7    55.7
7    71.4   192.7    55.7
8    71.4   192.7    55.9
10   64.8   176.8    54.3

## Simple Feature Scaling

In [ ]:
mydata['width'] = mydata['width']/mydata['width'].max()
mydata[['width', 'length', 'height']].head(10)

       width  length  height
0   0.890278   168.8    48.8
1   0.890278   168.8    48.8
2   0.909722   171.2    52.4
3   0.919444   176.6    54.3
4   0.922222   176.6    54.3
5   0.920833   177.3    53.1
6   0.991667   192.7    55.7
7   0.991667   192.7    55.7
8   0.991667   192.7    55.9
10  0.900000   176.8    54.3

## min-max

In [ ]:
mydata['length'] = (mydata['length'] - mydata['length'].min()) / (mydata['length'].max() - mydata['length'].min())
mydata[['width', 'length', 'height']].head(10)

       width    length  height
0   0.890278  0.413433    48.8
1   0.890278  0.413433    48.8
2   0.909722  0.449254    52.4
3   0.919444  0.529851    54.3
4   0.922222  0.529851    54.3
5   0.920833  0.540299    53.1
6   0.991667  0.770149    55.7
7   0.991667  0.770149    55.7
8   0.991667  0.770149    55.9
10  0.900000  0.532836    54.3

## z-score

In [ ]:
mydata['height'] = (mydata['height'] - mydata['height'].mean()) / mydata['height'].std()
mydata[['width', 'length', 'height']].head(10)

       width    length    height
0   0.890278  0.413433 -2.029015
1   0.890278  0.413433 -2.029015
2   0.909722  0.449254 -0.558319
3   0.919444  0.529851  0.217881
4   0.922222  0.529851  0.217881
5   0.920833  0.540299 -0.272351
6   0.991667  0.770149  0.789818
7   0.991667  0.770149  0.789818
8   0.991667  0.770149  0.871523
10  0.900000  0.532836  0.217881

# Convert Categorical to Numeric Values

In [ ]:
mydata.describe(include='object')

,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,engine-type,num-of-cylinders,fuel-system,price
count,201,201,201,201,201,201,201,201,201,201,201
unique,22,2,2,2,5,3,2,6,7,8,186
top,toyota,gas,std,four,sedan,fwd,front,ohc,four,mpfi,8921
freq,32,181,165,115,94,118,198,145,157,92,2

In [ ]:
mydata['fuel-type'].value_counts()

gas       181
diesel     20
Name: fuel-type, dtype: int64

In [ ]:
convert_fuel = pd.get_dummies(mydata['fuel-type'])
convert_fuel

     diesel  gas
0         0    1
1         0    1
2         0    1
3         0    1
4         0    1
..      ...  ...
200       0    1
201       0    1
202       0    1
203       1    0
204       0    1

[201 rows x 2 columns]

In [ ]:
df = pd.concat([mydata, convert_fuel], axis=1)
df

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,height,curb-weight,engine-type,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-L/100km,highway-L/100km,price,diesel,gas
0,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,0.413433,0.890278,-2.029015,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111.0,5000.0,11.190476,8.703704,13495,0,1
1,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,0.413433,0.890278,-2.029015,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111.0,5000.0,11.190476,8.703704,16500,0,1
2,1,122.0,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,0.449254,0.909722,-0.558319,2823,ohcv,six,152,mpfi,2.68,3.47,9.0,154.0,5000.0,12.368421,9.038462,16500,0,1
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,0.529851,0.919444,0.217881,2337,ohc,four,109,mpfi,3.19,3.40,10.0,102.0,5500.0,9.791667,7.833333,13950,0,1
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,0.529851,0.922222,0.217881,2824,ohc,five,136,mpfi,3.19,3.40,8.0,115.0,5500.0,13.055556,10.681818,17450,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,0.711940,0.956944,0.708112,2952,ohc,four,141,mpfi,3.78,3.15,9.5,114.0,5400.0,10.217391,8.392857,16845,0,1
201,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,0.711940,0.955556,0.708112,3049,ohc,four,141,mpfi,3.78,3.15,8.7,160.0,5300.0,12.368421,9.400000,19045,0,1
202,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,0.711940,0.956944,0.708112,3012,ohcv,six,173,mpfi,3.58,2.87,8.8,134.0,5500.0,13.055556,10.217391,21485,0,1
203,-1,95.0,volvo,diesel,turbo,four,sedan,rwd,front,109.1,0.711940,0.956944,0.708112,3217,ohc,six,145,idi,3.01,3.40,23.0,106.0,4800.0,9.038462,8.703704,22470,1,0
204,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,0.711940,0.956944,0.708112,3062,ohc,four,141,mpfi,3.78,3.15,9.5,114.0,5400.0,12.368421,9.400000,22625,0,1

In [ ]:
df.rename(columns={'diesel':'fuel_diesel', 'gas':'fuel_gas'}, inplace=True)
df

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,height,curb-weight,engine-type,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-L/100km,highway-L/100km,price,fuel_diesel,fuel_gas
0,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,0.413433,0.890278,-2.029015,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111.0,5000.0,11.190476,8.703704,13495,0,1
1,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,0.413433,0.890278,-2.029015,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111.0,5000.0,11.190476,8.703704,16500,0,1
2,1,122.0,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,0.449254,0.909722,-0.558319,2823,ohcv,six,152,mpfi,2.68,3.47,9.0,154.0,5000.0,12.368421,9.038462,16500,0,1
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,0.529851,0.919444,0.217881,2337,ohc,four,109,mpfi,3.19,3.40,10.0,102.0,5500.0,9.791667,7.833333,13950,0,1
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,0.529851,0.922222,0.217881,2824,ohc,five,136,mpfi,3.19,3.40,8.0,115.0,5500.0,13.055556,10.681818,17450,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,0.711940,0.956944,0.708112,2952,ohc,four,141,mpfi,3.78,3.15,9.5,114.0,5400.0,10.217391,8.392857,16845,0,1
201,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,0.711940,0.955556,0.708112,3049,ohc,four,141,mpfi,3.78,3.15,8.7,160.0,5300.0,12.368421,9.400000,19045,0,1
202,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,0.711940,0.956944,0.708112,3012,ohcv,six,173,mpfi,3.58,2.87,8.8,134.0,5500.0,13.055556,10.217391,21485,0,1
203,-1,95.0,volvo,diesel,turbo,four,sedan,rwd,front,109.1,0.711940,0.956944,0.708112,3217,ohc,six,145,idi,3.01,3.40,23.0,106.0,4800.0,9.038462,8.703704,22470,1,0
204,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,0.711940,0.956944,0.708112,3062,ohc,four,141,mpfi,3.78,3.15,9.5,114.0,5400.0,12.368421,9.400000,22625,0,1

In [ ]:
convert_aspiration = pd.get_dummies(mydata['aspiration'])
convert_aspiration

     std  turbo
0      1      0
1      1      0
2      1      0
3      1      0
4      1      0
..   ...    ...
200    1      0
201    0      1
202    1      0
203    0      1
204    0      1

[201 rows x 2 columns]

In [ ]:
df = pd.concat([df, convert_aspiration], axis=1)
df

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,height,curb-weight,engine-type,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-L/100km,highway-L/100km,price,fuel_diesel,fuel_gas,aspiration_std,aspiration_turbo
0,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,0.413433,0.890278,-2.029015,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111.0,5000.0,11.190476,8.703704,13495,0,1,1,0
1,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,0.413433,0.890278,-2.029015,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111.0,5000.0,11.190476,8.703704,16500,0,1,1,0
2,1,122.0,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,0.449254,0.909722,-0.558319,2823,ohcv,six,152,mpfi,2.68,3.47,9.0,154.0,5000.0,12.368421,9.038462,16500,0,1,1,0
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,0.529851,0.919444,0.217881,2337,ohc,four,109,mpfi,3.19,3.40,10.0,102.0,5500.0,9.791667,7.833333,13950,0,1,1,0
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,0.529851,0.922222,0.217881,2824,ohc,five,136,mpfi,3.19,3.40,8.0,115.0,5500.0,13.055556,10.681818,17450,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,0.711940,0.956944,0.708112,2952,ohc,four,141,mpfi,3.78,3.15,9.5,114.0,5400.0,10.217391,8.392857,16845,0,1,1,0
201,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,0.711940,0.955556,0.708112,3049,ohc,four,141,mpfi,3.78,3.15,8.7,160.0,5300.0,12.368421,9.400000,19045,0,1,0,1
202,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,0.711940,0.956944,0.708112,3012,ohcv,six,173,mpfi,3.58,2.87,8.8,134.0,5500.0,13.055556,10.217391,21485,0,1,1,0
203,-1,95.0,volvo,diesel,turbo,four,sedan,rwd,front,109.1,0.711940,0.956944,0.708112,3217,ohc,six,145,idi,3.01,3.40,23.0,106.0,4800.0,9.038462,8.703704,22470,1,0,0,1
204,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,0.711940,0.956944,0.708112,3062,ohc,four,141,mpfi,3.78,3.15,9.5,114.0,5400.0,12.368421,9.400000,22625,0,1,0,1

In [ ]:
df.rename(columns={'std':'std_aspiration', 'turbo':'turbo_aspiration'}, inplace=True)
df

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,height,curb-weight,engine-type,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-L/100km,highway-L/100km,price,fuel_diesel,fuel_gas,std_aspiration,turbo_aspiration
0,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,0.413433,0.890278,-2.029015,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111.0,5000.0,11.190476,8.703704,13495,0,1,1,0
1,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,0.413433,0.890278,-2.029015,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111.0,5000.0,11.190476,8.703704,16500,0,1,1,0
2,1,122.0,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,0.449254,0.909722,-0.558319,2823,ohcv,six,152,mpfi,2.68,3.47,9.0,154.0,5000.0,12.368421,9.038462,16500,0,1,1,0
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,0.529851,0.919444,0.217881,2337,ohc,four,109,mpfi,3.19,3.40,10.0,102.0,5500.0,9.791667,7.833333,13950,0,1,1,0
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,0.529851,0.922222,0.217881,2824,ohc,five,136,mpfi,3.19,3.40,8.0,115.0,5500.0,13.055556,10.681818,17450,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,0.711940,0.956944,0.708112,2952,ohc,four,141,mpfi,3.78,3.15,9.5,114.0,5400.0,10.217391,8.392857,16845,0,1,1,0
201,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,0.711940,0.955556,0.708112,3049,ohc,four,141,mpfi,3.78,3.15,8.7,160.0,5300.0,12.368421,9.400000,19045,0,1,0,1
202,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,0.711940,0.956944,0.708112,3012,ohcv,six,173,mpfi,3.58,2.87,8.8,134.0,5500.0,13.055556,10.217391,21485,0,1,1,0
203,-1,95.0,volvo,diesel,turbo,four,sedan,rwd,front,109.1,0.711940,0.956944,0.708112,3217,ohc,six,145,idi,3.01,3.40,23.0,106.0,4800.0,9.038462,8.703704,22470,1,0,0,1
204,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,0.711940,0.956944,0.708112,3062,ohc,four,141,mpfi,3.78,3.15,9.5,114.0,5400.0,12.368421,9.400000,22625,0,1,0,1

In [ ]:
df['num-of-doors'].value_counts()

four    115
two      86
Name: num-of-doors, dtype: int64

In [ ]:
df['num-of-doors'].replace('four', 4, inplace=True)
df['num-of-doors'].replace('two', 2, inplace=True)
df['num-of-doors'].head()

0    2
1    2
2    2
3    4
4    4
Name: num-of-doors, dtype: int64

In [ ]:
df.dtypes

symboling              int64
normalized-losses    float64
make                  object
fuel-type             object
aspiration            object
num-of-doors           int64
body-style            object
drive-wheels          object
engine-location       object
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
engine-type           object
num-of-cylinders      object
engine-size            int64
fuel-system           object
bore                 float64
stroke               float64
compression-ratio    float64
horsepower           float64
peak-rpm             float64
city-L/100km         float64
highway-L/100km      float64
price                 object
fuel_diesel            uint8
fuel_gas               uint8
std_aspiration         uint8
turbo_aspiration       uint8
dtype: object

In [ ]:
df.describe(include='object')

,make,fuel-type,aspiration,body-style,drive-wheels,engine-location,engine-type,num-of-cylinders,fuel-system,price
count,201,201,201,201,201,201,201,201,201,201
unique,22,2,2,5,3,2,6,7,8,186
top,toyota,gas,std,sedan,fwd,front,ohc,four,mpfi,8921
freq,32,181,165,94,118,198,145,157,92,2

# Data Binning

In [ ]:
df['price'] =  df['price'].astype('float')
df['price'].describe()

count      201.000000
mean     13207.129353
std       7947.066342
min       5118.000000
25%       7775.000000
50%      10295.000000
75%      16500.000000
max      45400.000000
Name: price, dtype: float64

In [ ]:
bins_price = np.linspace(df['price'].min(), df['price'].max(), num=4) # 3 categories required 4 bins
bins_price
# Low - 5118 ~ 18545.33333333
# Average - 18545.33333333 ~ 31972.66666667
# High - 31972.66666667 ~ 45400

array([ 5118.        , 18545.33333333, 31972.66666667, 45400.        ])

In [ ]:
label_names = ['Low price', 'Average price', 'High price']
df['price_Label'] = pd.cut(df['price'], bins_price, labels=label_names, include_lowest=True)
df[['price', 'price_Label']]

       price    price_Label
0    13495.0      Low price
1    16500.0      Low price
2    16500.0      Low price
3    13950.0      Low price
4    17450.0      Low price
..       ...            ...
200  16845.0      Low price
201  19045.0  Average price
202  21485.0  Average price
203  22470.0  Average price
204  22625.0  Average price

[201 rows x 2 columns]

In [ ]:
df

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,height,curb-weight,engine-type,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-L/100km,highway-L/100km,price,fuel_diesel,fuel_gas,std_aspiration,turbo_aspiration,price_Label
0,3,122.0,alfa-romero,gas,std,2,convertible,rwd,front,88.6,0.413433,0.890278,-2.029015,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111.0,5000.0,11.190476,8.703704,13495.0,0,1,1,0,Low price
1,3,122.0,alfa-romero,gas,std,2,convertible,rwd,front,88.6,0.413433,0.890278,-2.029015,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111.0,5000.0,11.190476,8.703704,16500.0,0,1,1,0,Low price
2,1,122.0,alfa-romero,gas,std,2,hatchback,rwd,front,94.5,0.449254,0.909722,-0.558319,2823,ohcv,six,152,mpfi,2.68,3.47,9.0,154.0,5000.0,12.368421,9.038462,16500.0,0,1,1,0,Low price
3,2,164.0,audi,gas,std,4,sedan,fwd,front,99.8,0.529851,0.919444,0.217881,2337,ohc,four,109,mpfi,3.19,3.40,10.0,102.0,5500.0,9.791667,7.833333,13950.0,0,1,1,0,Low price
4,2,164.0,audi,gas,std,4,sedan,4wd,front,99.4,0.529851,0.922222,0.217881,2824,ohc,five,136,mpfi,3.19,3.40,8.0,115.0,5500.0,13.055556,10.681818,17450.0,0,1,1,0,Low price
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95.0,volvo,gas,std,4,sedan,rwd,front,109.1,0.711940,0.956944,0.708112,2952,ohc,four,141,mpfi,3.78,3.15,9.5,114.0,5400.0,10.217391,8.392857,16845.0,0,1,1,0,Low price
201,-1,95.0,volvo,gas,turbo,4,sedan,rwd,front,109.1,0.711940,0.955556,0.708112,3049,ohc,four,141,mpfi,3.78,3.15,8.7,160.0,5300.0,12.368421,9.400000,19045.0,0,1,0,1,Average price
202,-1,95.0,volvo,gas,std,4,sedan,rwd,front,109.1,0.711940,0.956944,0.708112,3012,ohcv,six,173,mpfi,3.58,2.87,8.8,134.0,5500.0,13.055556,10.217391,21485.0,0,1,1,0,Average price
203,-1,95.0,volvo,diesel,turbo,4,sedan,rwd,front,109.1,0.711940,0.956944,0.708112,3217,ohc,six,145,idi,3.01,3.40,23.0,106.0,4800.0,9.038462,8.703704,22470.0,1,0,0,1,Average price
204,-1,95.0,volvo,gas,turbo,4,sedan,rwd,front,109.1,0.711940,0.956944,0.708112,3062,ohc,four,141,mpfi,3.78,3.15,9.5,114.0,5400.0,12.368421,9.400000,22625.0,0,1,0,1,Average price

In [ ]:
df['horsepower'].describe()

count    201.000000
mean     103.405534
std       37.365700
min       48.000000
25%       70.000000
50%       95.000000
75%      116.000000
max      262.000000
Name: horsepower, dtype: float64

In [ ]:
df.to_csv('clean_teleCust1000t')